### ISSUE TITLE
Object tags table cells are not cleared (anymore).

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#45] opened 2015-05-09 10:02 UTC
Previous text in cells is not cleared. For example prefilled text
"Edit this to add..." at the end of tags table is not cleared when clicking on the cell.
Also deleting any existing text in the cells (keys or values) leaves the deleted text visible.

This occoured after move from Debian 7 (Squeeze) to Debian 8 (Jessie). 
This happens with current master and also using source from early april. 
Merkaartor is built with qt4 as previously. Although qt5 exists at least partially on the system too.

Any ideas?

**Comment by Krakonos** [comment] 2015-05-13 09:29
It happens on my system as well, it probably is much older bug. I'll take a look.

**Comment by Krakonos** [comment] 2015-12-01 16:45
Fixed in 2353bd240cf2da6980aaa7faf8b77ea2e8cbfd20. At least the portion with empty string. It seems, that on every platform the "Edit this to add..." is handled correctly, and that includes Jessie 32bit (Qt5), Windows 64bit, and Gentoo 64bit (Qt4 & 5). Please, check if it's still a problem for you; also note that the text vanishes only after you enter edit node (double click).

**Comment by RM87** [comment] 2015-12-01 20:19
Works fine on Jessie with qt5 but still not with qt4.

**Comment by Krakonos** [comment] 2015-12-01 20:55
I tried on my laptop with sid/Qt4.8.7; works fine. What exactly happens? Is the overwriting OK, but the placeholder text does not vanish correctly?

**Comment by RM87** [comment] 2015-12-02 18:32
Overwriting ok, placeholder or previous writing does not vanish. Cell stays coloured blue and is writable on double click. Jessie with qt 4.8.7

**Comment by Krakonos** [comment] 2016-01-04 22:55
So, I have returned to this problem once again and I can't find anything wrong. Perhaps you could post a screenshot of what's wrong and what are you expecting to happen?

**Comment by RM87** [comment] 2016-01-05 15:45
text 'test' written over placeholder text
![image](https://cloud.githubusercontent.com/assets/859636/12119359/0170dae4-b3d4-11e5-9efd-2d7c3027b545.png)

**Comment by Krakonos** [comment] 2016-01-06 08:21
Thanks, that makes it so much clear. This never happened to me, I'll try to reproduce & fix it.

**Comment by jokuNimi** [comment] 2016-05-25 20:01
This bug affects me as well, version 0.18.2-78-gddec5c1-64bit, on arch, installed from merkaartor-git aur package. Text does not get deleted from view when it is replaced. The same thing happens for both the prelimenary 'Edit this to add' text, and when trying to edit an existing tag. Typing or selecting from the drop down menu makes no difference.

![editThisToAdd](https://cloud.githubusercontent.com/assets/8011580/15554217/afe1e562-22cb-11e6-868a-3c7b8a3cc6cb.png)
*'Test' written on top of prelimenary 'Edit this to add'*

![editingAnExistingTag](https://cloud.githubusercontent.com/assets/8011580/15554216/afdf12ba-22cb-11e6-9e4e-2fa6baf5f7b5.png)
*'Test' written on top of of existing tag text*

**Comment by Krakonos** [comment] 2016-05-25 22:07
Thanks. I still have no idea where is the problem, and I haven't been able to reproduce it myself.

Did this happen even with 0.18.2 release?

**Comment by jokuNimi** [comment] 2016-05-26 00:25
Yes, it happens with version 0.18.2 (or 0.18.2-78-gddec5c1-64bit as it says in help > about). That's the most recent version I could install for this computer (arch linux, git-merkaartor package). The problem is present with the plain merkaartor package as well. For some reason it's reporting the version as '-64bit', but I assume that that's 0.18.2 but slightly older.

On an ubuntu 16.04 virtual machine with the apt-get package (version 0.18.2), the bug isn't present. It might be an arch-specific issue.

**Comment by jokuNimi** [comment] 2016-05-26 00:54
The issue seems to be tied to theming. Changing my gtk-theme through gnome-tweak-tool solved the problem (specifically from [arc theme](https://github.com/horst3180/Arc-theme) to the [paper theme](https://github.com/snwh/paper-gtk-theme)).

**Comment by Krakonos** [comment] 2016-05-26 14:08
Great! This bug only appears in the Arc theme, not the default one. However, this is bad news as well, since the problem could be in Arc theme, qt, gtk/qt interafce (I have no idea how this theming works) or even some bad use/hack in Merkaartor itself (I think it's unlikely, since the elements used here are pretty much stock qt).

I'll report an issue in the Arc, as it's currently my most likely suspect, and see where it takes us.

**Comment by Krakonos** [comment] 2016-05-30 20:53
I have tested with the arc-theme master and it fixed the issue for me. Can you confirm?

**Comment by jokuNimi** [comment] 2016-05-30 22:31
It works with the latest arc theme version over here as well. Thanks!

**Comment by Krakonos** [comment] 2016-05-31 15:00
Thanks! @RM87 could you take a look as well? I'd like to know if there might be more themes with the same problem.

**Comment by Krakonos** [comment] 2016-06-01 08:55
Great, I consider it fixed for now. If you find any more problems, feel free to report them.

**Closed by Krakonos** 2016-06-01 08:55 UTC
Labels: Bug, Possibly fixed; requires confirmation
