### ISSUE TITLE
wrong reminder after upload

### ISSUE THREAD

**Issue by fkv1** [openstreetmap/merkaartor#277] opened 2022-09-15 11:25 UTC
When I save to an .mdc file and later upload my changes, and if then the upload is successfull, I get a message box that suggests to save the file after the upload. This doesn't make any sense because the changes can't be uploaded a second time. A reminder would be better _before_ the upload, just in case something goes wrong during the upload (e.g. Merkaartor crashes). But still I don't see why the reminder only comes if an .mdc file has previously been saved. I suggest to remove the reminder altogether, or to remind the user to save or upload when a certain number (e.g. 1000) of dirty objects have accumulated since the previous save or upload. Even better would be an autosave function. The interval (time or number of dirty objects) and filename would need to be configured in the settings.

**Comment by Krakonos** [comment] 2024-09-09 18:59
The reminder is there for a reason. I guess I should explain that in the dialog. The issue is, the document contains information on what data is dirty and what was uploaded. If you save, upload, open the saved document, the changes already uploaded are still marked dirty and when re-uploaded, they will create duplicate geometry in case of new objects.

**Comment by Krakonos** [comment] 2024-10-02 20:31
Merged to master, will be release as part of 0.20.1

**Closed by Krakonos** 2024-10-02 20:31 UTC
