### ISSUE TITLE
"make release" does not work!

### ISSUE THREAD

**Issue by M-Reimer** [openstreetmap/merkaartor#41] opened 2015-05-03 19:15 UTC
I'm trying to build a version of Merkaartor that can be installed into my Linux system.

I did so using "make release" (which, by the way, is documented nowhere!) and this doesn't work at all. I still get a build that tries to search for the plugins at a path that doesn't exist at all...

**Comment by Krakonos** [comment] 2015-05-03 19:25
Well, it is mentioned in the INSTALL file. The problem is, that 'make release' sets up the plugin path according to the PREFIX, and the plugins are installed only after 'make install'. If this happens after you've make installed, please, post your qmake/make commands and some output that indicates -PLUGINS_DIR content while compiling.

In theory, I could make it check the binaries/bin/plugins even in release mode (as the Windows version does). I'll do that right now, as it makes sense.

**Comment by M-Reimer** [comment] 2015-05-03 19:29
I don't know if this is really a good idea. There has been a Windows bug that "DLL injection or something like that" that could be abused by loading DLL files from the working directory. Maybe we would have a similar issue if we load *.so files from a path relative to the working directory?

**Comment by M-Reimer** [comment] 2015-05-03 19:31
The problem is not loading from two different paths, the problem is that loading from the "real" plugin path doesn't work...

**Comment by Krakonos** [comment] 2015-05-03 19:37
Yes, it's definitely out of question on Windows. On linux, I was thinking along the lines "try the real path, if it does not exist, try the application path+/plugins". On regular installation, that would fail, since no regular user is able to write into '/usr/bin/plugins', and if someone could, you're doomed anyway.

On building from repository and running ./binaries/bin/merkaartor, that would work as expected. If someone downloads untrusted binary there, well,... I can't help him.

**Comment by M-Reimer** [comment] 2015-05-03 19:39
Maybe still a bad idea. If I install one release to my system and decide to compile a second for testing/debugging in my $HOME, then my debug version tries to load "old" plugins. Worst-Case the interface has changed and I get unexpected crashes.

I think one path should be enough.

**Comment by M-Reimer** [comment] 2015-05-03 19:41
I execute the following commands:

  lrelease-qt5 src/src.pro
  qmake-qt5 -r PREFIX='/usr'
  make release

For some reason I still get the plugin directory below the source path:
-DPLUGINS_DIR=/home/myuser/merkaartor-git/src/../binaries//bin/plugins

And after compiling the "make" process ends with a nonzero exit status.

**Comment by M-Reimer** [comment] 2015-05-03 19:43
"make release" is documented but only in the "master" branch so I didn't see this. I'm compiling the "qt5" branch.

**Comment by Krakonos** [comment] 2015-05-03 20:09
I see the bug. The problem seems to be in how debug_and_release is handled in qmake. The documentations states, that if you put debug or release into config, it is the default if you type 'make'. Unfortunately, it is not and even your make release ends up with some debug defines. Still looking into it.

Btw. I've already merge the qt5 branch into master, and made some further improvements. I will be removing it soon, as the qt5 seems to be working nicely.

**Comment by Krakonos** [comment] 2015-05-03 21:12
Try with branch plugins-dir. I've changed the behavior to what I proposed. I will add a macro that can be defined to override this precedence, for use in distributions that may need it (the only problem I see is when a distributioun would have /usr/bin/plugins; I hope there are none).

**Comment by M-Reimer** [comment] 2015-05-13 08:48
This seems to fix this problem, but I'm still not sure whether this is a good idea to search from two paths. I think if "make release" and "make debug" would just work and the debug build searches from the "subdirectory", then this would be OK as long as it is possible to make "make debug" the default. If someone really wants to install some software to his system, then I think he will read the INSTALL file anyway. The biggest majority will just use prebuilt packages.

**Comment by Krakonos** [comment] 2015-05-13 08:54
Well, the problem is you can't choose your default, the default is whatever Qt is built as. I'll keep it this way until I find a better solution. Feel free to suggest one.

**Comment by M-Reimer** [comment] 2015-05-13 09:24
At least in the short run I can't think of any better solution. Maybe in future something better will show up. Could you please merge your changes to the master tree as soon as possible? I'm working on creating a build script and would like to point it directly to the "master" branch.

**Comment by Krakonos** [comment] 2015-05-13 09:27
Merged.

**Closed by Krakonos** 2015-05-13 09:27 UTC
